project:
  type: book

book:
  title: "Anova_Ancova"
  author: "Monika Avila Marquez"
  date: "9/19/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - ANOVA.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    include-in-header:
      - text: |
          \usepackage{amsmath}
      - file: packages.tex
      - macros.tex 
    documentclass: scrreprt
    
    

editor: visual

